import os
os.system ('clear')
os.system ('clear')
os.system ('sl')
os.system('clear')
print ('\033[1;36mحﺎﭴﻧﺑ مﺗ')
os.system ('figlet HK Gmail')
print ("")
print ("")
print (" \033[1;32m بﺎﺴﺤ مﺴإ  \033[1;33m: zouhair ettaher")
print ("")
print ("")
print (" \033[1;32mفﺗﺎﮩﻟ مﻗر/ ﺪﯾﺮﺑ \033[1;33m: ettaherzouhair@gmail.com")
print ("")
print ("")
print (" \033[1;32mﺮﺴㅤﺔﻤﻠڪ :\033[1;33m Wdadi1977@//dimawac")
print ("")
print ("")
print ("")
print ("")
os.system ('figlet')
