import os
os.system ('clear')
os.system ('clear')
os.system ('sl')
os.system ('clear')
os.system ('figlet HK Free Fire')
print ("")
print ("")
print ("")
print ("")
print (" \033[1;32mname faecbook \033[1;31m: gmail بﺎﺴﺤ")
print ("")
print ("")
print (" \033[1;32memail \033[1;31m: gmail بﺎﺴﺤ")
print ("")
print ("")
print (" \033[1;32mpasswerd :\033[1;31m gmail بﺎﺴﺤ")
print ("")
print ("")
os.system ('figlet')
